# Generated by Django 5.2.4 on 2025-07-03 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("bp_sys", "Blood Pressure - Systolic"),
                            ("bp_dia", "Blood Pressure - Diastolic"),
                            ("glucose", "Blood Glucose"),
                            ("heart_rate", "Heart Rate"),
                            ("saturation", "Oxygen Saturation"),
                            ("steps", "Steps"),
                            ("weight", "Weight"),
                            ("height", "Height"),
                            ("temperature", "Body Temperature"),
                            ("body_fat", "Body Fat Percentage"),
                            ("custom", "Custom"),
                            ("dummy", "Dummy"),
                        ],
                        default="dummy",
                        max_length=20,
                    ),
                ),
                ("type_other", models.CharField(blank=True, max_length=20, null=True)),
                ("value", models.FloatField()),
                ("unit", models.CharField(max_length=20)),
                ("recorded_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MAL", "Male"),
                            ("FEM", "Female"),
                            ("TMA", "Trans Male"),
                            ("TFE", "Trans female"),
                            ("OTR", "Other"),
                            ("UNK", "Unknown"),
                        ],
                        default="UNK",
                        max_length=3,
                    ),
                ),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_kg", models.FloatField(blank=True, null=True)),
                ("height_cm", models.FloatField(blank=True, null=True)),
                (
                    "chronic_conditions",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list (e.g., hypertension, diabetes)",
                    ),
                ),
                (
                    "activity_level",
                    models.CharField(
                        choices=[
                            ("sedentary", "Sedentary"),
                            ("light", "Light"),
                            ("moderate", "Moderate"),
                            ("intense", "Intense"),
                            ("athlete", "Athlete"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
