# Generated by Django 5.2.4 on 2025-07-06 04:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_goal_created_at_goal_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goal',
            new_name='MetaPersonal',
        ),
        migrations.RenameModel(
            old_name='Notification',
            new_name='NotificacionSimulada',
        ),
    ]
